---
- hosts: 172.16.44.116
  tasks:

      - name: apt update
        apt: update_cache=yes cache_valid_time=3600
        register: apt_result
        until: apt_result|success
        retries: 3
        delay: 1
        ignore_errors: yes

      - name: retry if needed using command apt-get update
        command: apt-get update
        when: apt_result|failed
     
      - name: Install a list of package for OpenSCAP
        apt:
          name: libopenscap8
          state: latest

      - name: Install a list of package for OpenSCAP - 2
        apt:
          name: xsltproc
          state: latest






