---
- hosts: 10.128.1.160
  tasks:

      - name: change wazuh local_internal_options.conf
        command: sed -i '/logcollector.remote/c\logcollector.remote_commands=1' /var/ossec/etc/local_internal_options.conf
        command: sed -i '/wazuh_command.remote/c\wazuh_command.remote_commands=1' /var/ossec/etc/local_internal_options.conf

      - name: Restart service wazuh-agent, in all cases
        service:
               name: wazuh-agent
               state: restarted
               enabled: yes







